theme: minima
title: TEMMPORARY PERSONAL SITE
author: Jackson Reynolds
email: jwreynold@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a temporary site for my portfolio webpage. Soon to be @ jackson-reynolds.us

# social links
twitter_username: im_zewalrus
github_username:  JacksonReynolds

show_excerpts: false # set to false to remove excerpts on the homepage
